<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/protos/teste.proto

namespace App\Services\TestStore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Services.TestStore.TesteRequest</code>
 */
class TesteRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Protos\Teste::initOnce();
        parent::__construct($data);
    }

}

