<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources/protos/teste.proto

namespace App\Services\TestStore;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Services.TestStore.TesteResponse</code>
 */
class TesteResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string foo = 1;</code>
     */
    protected $foo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $foo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Resources\Protos\Teste::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string foo = 1;</code>
     * @return string
     */
    public function getFoo()
    {
        return $this->foo;
    }

    /**
     * Generated from protobuf field <code>string foo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFoo($var)
    {
        GPBUtil::checkString($var, True);
        $this->foo = $var;

        return $this;
    }

}

